import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { UserInfoProvider } from "@/app/hooks/user/userInfoContext"; // UserProvider をインポート
import { PostInfoProvider } from "@/app/hooks/post/postInfoContext"; // PostProvider をインポート
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <UserInfoProvider>
          <PostInfoProvider>{children}</PostInfoProvider> {/* ラッパー追加 */}
        </UserInfoProvider>
      </body>
    </html>
  );
}
