services:
  nextjs:
    build:
      context: ./frontend # Dockerfile があるディレクトリ
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Next.js アプリ用
      - "6006:6006" # Storybook 用
    volumes:
      - ./frontend:/app # ホスト側のコードをコンテナ内にマウント
      - /app/node_modules # node_modules をコンテナ内で管理
    environment:
      NODE_ENV: development
    command: sh -c "yarn install && yarn dev & yarn storybook --ci"

  go:
    build:
      context: ./backend # Dockerfile があるディレクトリ
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # API サーバー用s
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/unitimetable?sslmode=disable" # PostgreSQL 接続情報

  db:
    image: postgres:15 # PostgreSQL の公式イメージ
    container_name: unitimetable-db
    ports:
      - "5432:5432" # PostgreSQL のデフォルトポート
    environment:
      POSTGRES_USER: postgres # デフォルトユーザー
      POSTGRES_PASSWORD: password # デフォルトパスワード
      POSTGRES_DB: unitimetable # 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
